[package]
name = "mirador"
description = "CLI to watch mailbox changes"
version = "0.1.0"
authors = ["Clément DOUIN (soywod) <clement.douin@posteo.net>"]
rust-version = "1.89"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "email"]
keywords = ["cli", "email", "watch", "imap", "jmap"]
homepage = "https://pimalaya.org"
documentation = "https://pimalaya.org/mirador/cli/latest"
repository = "https://github.com/pimalaya/mirador"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rustls-ring", "imap", "jmap", "maildir"]
imap = ["dep:io-imap", "io-imap/client", "pimalaya-cli/imap"]
jmap = ["dep:base64", "dep:io-jmap", "io-jmap/client", "pimalaya-cli/jmap"]
maildir = ["dep:io-maildir", "io-maildir/client", "io-maildir/parser"]
native-tls = ["pimalaya-stream/native-tls", "io-imap?/native-tls", "io-jmap?/native-tls"]
rustls-aws = ["pimalaya-stream/rustls-aws", "io-imap?/rustls-aws", "io-jmap?/rustls-aws"]
rustls-ring = ["pimalaya-stream/rustls-ring", "io-imap?/rustls-ring", "io-jmap?/rustls-ring"]
vendored = ["pimalaya-stream/vendored", "notify-rust/d_vendored"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"] }

[dependencies]
anyhow = "1"
base64 = { version = "0.23", optional = true }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
ctrlc = { version = "3", features = ["termination"] }
io-imap = { version = "0.5", default-features = false, optional = true }
io-jmap = { version = "0.3", default-features = false, optional = true }
io-maildir = { version = "0.3", default-features = false, optional = true }
io-sasl = { version = "0.1", default-features = false, features = ["scram"] }
log = "0.4"
notify-rust = { version = "4", default-features = false, features = ["d"] }
pimalaya-cli = { version = "0.2", default-features = false, features = ["terminal", "spinner"] }
pimalaya-config = { version = "0.1", default-features = false, features = ["toml", "secret"] }
pimalaya-stream = { version = "0.3", default-features = false, features = ["std"] }
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
subst = "0.3"
url = { version = "2.2", features = ["serde"] }

[patch.crates-io]
io-imap.git = "https://github.com/pimalaya/io-imap"
